# executable files for this directory
OBJECTS = compounddecls.exe convs.exe dbl_ptr.exe \
		  escape.exe inits.exe \
		  literals.exe ref-ex.exe Sales_data.exe \
		  scope_levels.exe unsigned.exe

# these executables are not made by default;
# the corresponding source file uses c++ 11 features
C11_OBJECTS = decl-ex.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

LOCFLAGS = -I../1
